# Generated by Django 3.0.8 on 2020-07-12 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default='', max_length=100)),
                ('institution_city', models.CharField(default='', max_length=100)),
                ('institution_state', models.CharField(default='', max_length=2)),
                ('institution_year_founded', models.IntegerField(default=2020)),
                ('logo', models.ImageField(default='default_institution_logo.png', upload_to='logos')),
                ('approved', models.BooleanField(default=False)),
                ('unique_members', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('school_year', models.CharField(default='', max_length=9)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yearbook.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionYearProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearbook_picture', models.ImageField(default='default_profile_picture.png', upload_to='yearbook_pictures')),
                ('yearbook_quote', models.CharField(default='', max_length=140)),
                ('institution_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yearbook.InstitutionYear')),
            ],
        ),
        migrations.CreateModel(
            name='YearbookUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default_profile_picture.png', upload_to='avatars')),
                ('bio', models.CharField(default='', max_length=140)),
                ('friends', models.ManyToManyField(blank=True, to='yearbook.YearbookUser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=280)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yearbook.YearbookUser')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yearbook.InstitutionYearProfile')),
            ],
        ),
        migrations.AddField(
            model_name='institutionyearprofile',
            name='yearbook_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yearbook.YearbookUser'),
        ),
    ]
