# Generated by Django 3.0.5 on 2020-04-30 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0002_auto_20200430_2144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='InstitutionYearProfile',
        ),
    ]
