# Generated by Django 3.0.5 on 2020-05-01 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0003_auto_20200430_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yearbook.YearbookUser')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yearbook.InstitutionYearProfile')),
            ],
        ),
    ]
