# Generated by Django 3.0.5 on 2020-05-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0004_signatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='institution_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='institution',
            name='institution_state',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='institutionyear',
            name='school_year',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='institutionyear',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='institutionyearprofile',
            name='is_educator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='signatures',
            name='signature',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='yearbookuser',
            name='bio',
            field=models.TextField(default='', max_length=140),
        ),
    ]
