# Generated by Django 3.0.5 on 2020-05-01 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0005_auto_20200501_1311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signatures',
            new_name='Signature',
        ),
    ]
