# Generated by Django 3.0.5 on 2020-05-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0006_auto_20200501_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionyearprofile',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='avatars'),
        ),
    ]
