# Generated by Django 3.0.5 on 2020-05-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0007_institutionyearprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionyearprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='institutionyearprofile',
            name='yearbook_picture',
            field=models.ImageField(default='default.png', upload_to='yearbook_pictures'),
        ),
        migrations.AddField(
            model_name='yearbookuser',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='avatars'),
        ),
    ]
