# Generated by Django 3.0.5 on 2020-05-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0008_auto_20200507_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='institution_year_founded',
            field=models.IntegerField(default=2020),
        ),
    ]
