# Generated by Django 3.0.5 on 2020-05-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0009_institution_institution_year_founded'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='unique_members',
            field=models.IntegerField(default=0),
        ),
    ]
