# Generated by Django 3.0.5 on 2020-05-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0010_institution_unique_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionyearprofile',
            name='yearbook_quote',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='signature',
            name='signature',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='yearbookuser',
            name='bio',
            field=models.CharField(default='', max_length=140),
        ),
    ]
