# Generated by Django 3.0.5 on 2020-05-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0012_institution_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionyearprofile',
            name='yearbook_picture',
            field=models.ImageField(default='default_profile_picture.png', upload_to='yearbook_pictures'),
        ),
        migrations.AlterField(
            model_name='yearbookuser',
            name='avatar',
            field=models.ImageField(default='default_profile_picture.png', upload_to='avatars'),
        ),
    ]
