# Generated by Django 3.0.5 on 2020-05-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0014_auto_20200518_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearbookuser',
            name='bio',
            field=models.CharField(max_length=140),
        ),
    ]
