# Generated by Django 3.0.5 on 2020-05-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0015_auto_20200519_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearbookuser',
            name='bio',
            field=models.CharField(default='', max_length=140),
        ),
    ]
