# Generated by Django 3.0.5 on 2020-05-21 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0016_auto_20200519_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionyearprofile',
            name='is_educator',
        ),
    ]
