# Generated by Django 3.0.5 on 2020-05-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0017_remove_institutionyearprofile_is_educator'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
