# Generated by Django 3.0.5 on 2020-05-28 22:17

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('yearbook', '0018_institution_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionyearprofile',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
