# Generated by Django 3.0.5 on 2020-05-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0019_institutionyearprofile_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearbookuser',
            name='friends',
            field=models.ManyToManyField(to='yearbook.YearbookUser'),
        ),
    ]
