# Generated by Django 3.0.5 on 2020-05-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0020_yearbookuser_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearbookuser',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, to='yearbook.YearbookUser'),
        ),
    ]
