# Generated by Django 3.0.5 on 2020-06-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0021_auto_20200529_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearbookuser',
            name='friends',
            field=models.ManyToManyField(blank=True, to='yearbook.YearbookUser'),
        ),
    ]
